### ISSUE TITLE
Failed to fetch files. 

### ISSUE THREAD

**Issue by paolodedomini** [loganwishartcraig/gatsby-source-directus-cms#1]
i grant all the read permission on all the directus fields but :

`error GSD_CMS error Failed to fetch files.
error GSD_CMS error Did you grant READ permissions?
error GSD_CMS error Failed to build Directus nodes { e: TypeError: data.flat is not a function
    at DirectusService.<anonymous> (/mnt/h/lavori/clienti/interna/2019/website/gatsby-starter/node_modules/gatsby-source-directus-cms/directus-service/index.js:188:29)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/h/lavori/clienti/interna/2019/website/gatsby-starter/node_modules/gatsby-source-directus-cms/directus-service/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) }`
Any idea? thanks

**Comment by loganwishartcraig** [comment]
Hi!

Looks like I wasn't covering some cases where the Directus SDK was returning null.

I've updated the package to **1.0.3** and redeployed to npm.

Could you re-install and try again?

Thanks, let me know!

**Comment by paolodedomini** [comment]
from the terminal:
(it seems to be a file problem but i granted the public access to them too)

`GSD_CMS info Starting...
GSD_CMS info Target: http://mokacms.monemacms.it//mokacms
GSD_CMS warning No authentication details provided. Will try using the public API...
GSD_CMS info Initializing Directus Service...
GSD_CMS info Fetching all collections...
GSD_CMS info Fetching all records...
GSD_CMS info Fetching records for AboutUs...
GSD_CMS info Fetching records for Contatti...
GSD_CMS info Fetching records for Menu...
GSD_CMS info Fetching records for Mission...
GSD_CMS info Fetching records for News...
GSD_CMS info Fetching records for Progetti...
GSD_CMS info Fetching records for progetti_strumenti...
GSD_CMS info Fetching records for strumenti...
GSD_CMS info Fetching records for test...
GSD_CMS info Fetching all relations...
GSD_CMS info Fetching all files...
error GSD_CMS error Failed to fetch files.
error GSD_CMS error Did you grant READ permissions?
error GSD_CMS error Failed to build Directus nodes { e: TypeError: data.flat is not a function
    at DirectusService.<anonymous> (/mnt/c/lavoro/monema2019/node_modules/gatsby-source-directus-cms/directus-service/index.js:189:29)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/c/lavoro/monema2019/node_modules/gatsby-source-directus-cms/directus-service/index.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) }
warning The gatsby-source-directus-cms plugin has generated no Gatsby nodes. Do you need it?`

Thank you so much for the answer

**Comment by loganwishartcraig** [comment]
Oh, what version of node are you running?

It might be because I'm using Array.prototype.flat() which is only supported in v11.0.0+.

I've included a polyfill and redeployed.

Could you install **v1.0.4** and give it another go?

**Comment by paolodedomini** [comment]
ok now everything is working fine.
I'm testing directus + gatsbyjs + netlify and your plugin is an imoortant part of this jamstack system.
I hope to use it in production for some projects in the near future so i will credit your work and support properly.
I think i owe you a beer or a bottle of wine(we're in italy so maybe wine is a better choice...). or two,
Anyway: thanks.

**Comment by loganwishartcraig** [comment]
Awesome! Glad everything is working. Feel free to open more issues/feature requests if they come up. Good luck with the projects!
